[package]
name = "linter-server"
version = "0.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmium-libs-lsp-handler = { path = "../../../../../libs/lsp-handler", version = "0.0.1" }
solidhunter-lib = { path = "../linter-lib", version = "0.0.2" }
js-sys = "0.3.64"