on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
        description: "yarn workspace name"
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
      VSCE_PAT:
        required: true
  workflow_dispatch:
    inputs:
      workspace:
        required: true
        type: string
        description: "yarn workspace name"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
            #container: ubuntu:18.04
          #- os: ubuntu-20.04
          #  target: aarch64-unknown-linux-gnu
          #  code-target: linux-arm64
          #- os: ubuntu-20.04
          #  target: arm-unknown-linux-gnueabihf
          #  code-target: linux-armhf
          - os: macos-11
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: macos-11
            target: aarch64-apple-darwin
            code-target: darwin-arm64
    runs-on: ${{ matrix.os }}
    #container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get tags
        run: git fetch --tags origin

      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - id: setup-yarn
        # Install yarn 3 & workspace-tools
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn -v

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Get tag prefix
        id: get-tag-prefix
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const workspace = "${{ inputs.workspace }}";
            const language = workspace.split('-')[1];
            return language;

      - name: Retrieve version
        id: retrieve-version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: "${{ steps.get-tag-prefix.outputs.result }}-"

      - name: Extract semver
        uses: actions/github-script@v6
        id: tag
        with:
          result-encoding: string
          script: |
            const tag = '${{ steps.retrieve-version.outputs.tag }}';
            const semver = tag.split('-')[1];
            return semver;
      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build
        run: |
          yarn workspace ${{ inputs.workspace }} build
        env:
          CARGO_BUILD_TARGET: ${{ matrix.target }}

      - name: Publish
        run: yarn workspace ${{ inputs.workspace }} run extension:publish ${{ github.ref_name == 'dev' && '--pre-release' || '' }} ${{ steps.tag.outputs.result }} --target ${{matrix.code-target}} 
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          